<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9Ck6Jnd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9Ck6Jnd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9Ck6Jnd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9Ck6Jnd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9Ck6Jnd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9Ck6Jnd',
    'container.build_id' => '30875ed2',
    'container.build_time' => 1605727640,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9Ck6Jnd');
